// ========== Lead Required Fields ==========
export const REQUIRED_LEAD_FIELDS = [
  "propertyType",
  "bhk",
  "location",
  "budget",
  "timeline",
] as const;

// ========== Site Visit Affirmative Patterns ==========
export const SITE_VISIT_AFFIRMATIVE_PATTERNS = [
  "haan",
  "ha",
  "yes",
  "haan ji",
  "hanji",
  "ok",
  "okay",
  "ready",
  "ready hu",
  "ready hai",
  "taiyar hai",
  "taiyar hu",
  "chalo",
  "chaliye",
  "abhi karte hain",
  "bilkul",
  "theek hai",
  "sahi hai",
  "ji haan",
  "i am ready",
  "let's go",
  "sure",
  "confirmed",
  "done",
  "chalega",
  "ham ready",
  "hum ready",
  "hai taiyaar",
  "taiyaar h",
  "taiyar h",
] as const;

// ========== Greeting Words (filter out from names) ==========
export const GREETING_WORDS = new Set([
  "hi",
  "hii",
  "hello",
  "hey",
  "hlo",
  "helo",
  "namaste",
  "namaskar",
  "ram ram",
  "pranam",
]);

// ========== Opt‑Out Phrases ==========
export const OPT_OUT_PHRASES = [
  "stop",
  "band karo",
  "unsubscribe",
  "don't contact",
  "hato",
  "delete karo",
  "remove me",
  "quit",
  "exit",
  "no more messages",
] as const;

// ========== Hinglish Words (for language detection) ==========
export const HINGLISH_WORDS = new Set([
  "kya",
  "hai",
  "hain",
  "mujhe",
  "chahiye",
  "leke",
  "denge",
  "kar",
  "ka",
  "ki",
  "mein",
  "aap",
  "aapko",
  "hum",
  "humein",
  "batao",
  "dekho",
  "suno",
  "jao",
  "karo",
  "hoga",
  "hogi",
  "honge",
  "tha",
  "thi",
  "the",
  "karna",
  "karte",
  "karti",
  "hu",
  "mai",
  "tum",
  "tumhara",
  "apna",
  "yeh",
  "woh",
  "nahi",
  "na",
  "ji",
  "haan",
  "are",
  "aur",
  "bhi",
  "hi",
  "toh",
  "tho",
  "par",
]);

// ========== Casual Greetings (short, treated as Hinglish) ==========
export const CASUAL_GREETINGS = new Set([
  "hi",
  "hii",
  "hello",
  "hey",
  "hlo",
  "helo",
  "namaste",
  "namaskar",
  "ram ram",
]);
