export interface LocalityData {
  name: string;
  area: string;
  pincode: string;
  isNearITHub: boolean;
  buyRange: string; 
  rentRange: string; 
  landmarks: string[];
  commuteMap?: Record<string, string>;
}

export const HYDERABAD_LOCALITIES: LocalityData[] = [
  {
    name: "Gachibowli",
    area: "West Zone",
    pincode: "500032",
    isNearITHub: true,
    buyRange: "65-150 Lakhs",
    rentRange: "18k-45k",
    landmarks: ["IT Park", "Financial District", "University of Hyderabad"],
    commuteMap: { "HITEC City": "5 km", "Financial District": "2 km" },
  },
  {
    name: "Kondapur",
    area: "West Zone",
    pincode: "500084",
    isNearITHub: true,
    buyRange: "50-120 Lakhs",
    rentRange: "15k-35k",
    landmarks: ["Kondapur Main Road", "Botanical Garden"],
    commuteMap: { "HITEC City": "4 km", Gachibowli: "3 km" },
  },
  {
    name: "HITEC City",
    area: "West Zone",
    pincode: "500081",
    isNearITHub: true,
    buyRange: "70-160 Lakhs",
    rentRange: "20k-50k",
    landmarks: ["Cyber Towers", "L&T Infocity", "Hitex Exhibition Center"],
  },
  {
    name: "Kukatpally",
    area: "North West Zone",
    pincode: "500085",
    isNearITHub: false,
    buyRange: "35-75 Lakhs",
    rentRange: "10k-22k",
    landmarks: ["Kukatpally Housing Board", "KPHB Colony", "JNTU"],
    commuteMap: { "HITEC City": "12 km" },
  },
  {
    name: "Miyapur",
    area: "North West Zone",
    pincode: "500049",
    isNearITHub: false,
    buyRange: "32-70 Lakhs",
    rentRange: "9k-20k",
    landmarks: ["Miyapur X Roads", "Metro Station"],
    commuteMap: { "HITEC City": "14 km" },
  },
  {
    name: "Nallagandla",
    area: "West Zone",
    pincode: "500019",
    isNearITHub: true,
    buyRange: "45-100 Lakhs",
    rentRange: "12k-30k",
    landmarks: ["ORR Junction", "Tellapur"],
    commuteMap: { Gachibowli: "6 km", "Financial District": "7 km" },
  },
  {
    name: "Manikonda",
    area: "West Zone",
    pincode: "500089",
    isNearITHub: true,
    buyRange: "40-90 Lakhs",
    rentRange: "11k-28k",
    landmarks: ["Lanco Hills", "Manikonda Jogging Track"],
    commuteMap: { Gachibowli: "5 km" },
  },
  {
    name: "Financial District",
    area: "West Zone",
    pincode: "500032",
    isNearITHub: true,
    buyRange: "80-200 Lakhs",
    rentRange: "25k-55k",
    landmarks: ["Wework", "Amazon Campus", "ICICI Bank Tower"],
  },
  {
    name: "Madhapur",
    area: "West Zone",
    pincode: "500081",
    isNearITHub: true,
    buyRange: "55-130 Lakhs",
    rentRange: "16k-40k",
    landmarks: ["Kavuri Hills", "Jubilee Hills Checkpost"],
    commuteMap: { "HITEC City": "2 km" },
  },
  {
    name: "Kothaguda",
    area: "West Zone",
    pincode: "500092",
    isNearITHub: true,
    buyRange: "50-110 Lakhs",
    rentRange: "14k-32k",
    landmarks: ["Kothaguda Cross Roads", "SLN Terminus"],
    commuteMap: { "HITEC City": "3 km" },
  },
  {
    name: "Bachupally",
    area: "North West Zone",
    pincode: "500090",
    isNearITHub: false,
    buyRange: "30-65 Lakhs",
    rentRange: "8k-18k",
    landmarks: ["Bachupally Lake", "Pragathi Nagar"],
  },
  {
    name: "Nizampet",
    area: "North West Zone",
    pincode: "500090",
    isNearITHub: false,
    buyRange: "32-68 Lakhs",
    rentRange: "9k-19k",
    landmarks: ["Nizampet Village", "Gardens Mall"],
  },
  {
    name: "Pragathi Nagar",
    area: "North West Zone",
    pincode: "500090",
    isNearITHub: false,
    buyRange: "28-60 Lakhs",
    rentRange: "8k-16k",
    landmarks: ["Pragathi Nagar Ground", "Bachupally Road"],
  },
  {
    name: "Tellapur",
    area: "West Zone",
    pincode: "502032",
    isNearITHub: false,
    buyRange: "38-85 Lakhs",
    rentRange: "10k-24k",
    landmarks: ["Tellapur ORR Exit", "My Home Bhooja"],
    commuteMap: { Gachibowli: "8 km" },
  },
  {
    name: "Patancheru",
    area: "West Zone",
    pincode: "502319",
    isNearITHub: false,
    buyRange: "22-50 Lakhs",
    rentRange: "6k-14k",
    landmarks: ["Industrial Area", "Sangareddy Road"],
  },
  {
    name: "Banjara Hills",
    area: "Central Zone",
    pincode: "500034",
    isNearITHub: false,
    buyRange: "150-400 Lakhs",
    rentRange: "45k-120k",
    landmarks: ["Road No. 12", "Jubilee Hills", "LV Prasad Eye Institute"],
  },
  {
    name: "Jubilee Hills",
    area: "Central Zone",
    pincode: "500033",
    isNearITHub: false,
    buyRange: "200-500 Lakhs",
    rentRange: "60k-150k",
    landmarks: ["Jubilee Hills Checkpost", "Road No. 36", "TV Tower"],
  },
  {
    name: "Madhuranagar",
    area: "Central Zone",
    pincode: "500028",
    isNearITHub: false,
    buyRange: "60-120 Lakhs",
    rentRange: "15k-30k",
    landmarks: ["Yousufguda Junction", "SR Nagar"],
  },
  {
    name: "SR Nagar",
    area: "Central Zone",
    pincode: "500038",
    isNearITHub: false,
    buyRange: "50-100 Lakhs",
    rentRange: "12k-25k",
    landmarks: ["SR Nagar Metro", "Ameerpet"],
  },
  {
    name: "Ameerpet",
    area: "Central Zone",
    pincode: "500038",
    isNearITHub: false,
    buyRange: "55-110 Lakhs",
    rentRange: "13k-28k",
    landmarks: ["Ameerpet Metro", "IT Hub (Training)"],
  },
];
